### ISSUE TITLE
Update preview on blur

### ISSUE THREAD

**Issue by arnoson** [kirby-tools/community#23]
### Describe the feature

Updating the preview while typing in text fields/blocks can be a bit laggy for more complex pages. It would be great if there would be an option to disable the interval-based update and use blur events on any text fields/blocks instead.

### Final checks

- [X] Check existing [issues](https://github.com/kirby-tools/community/issues).

**Comment by johannschopplich** [comment]
Hi Arno!

Thanks for the feature request. I like it a lot. I've just released v1.5.0 of the Live Preview plugin with a new section property: The `updateStrategy` property allows you to control how the preview is updated when changes are made to the content. The following update strategies are available:

- `interval`: The preview is updated at a fixed interval. By default, the preview is updated every 250 milliseconds (0.25 seconds). You can adjust the update interval using the `updateInterval` property.
- `blur`: The preview is updated when any Kirby text-like, number-like, or blocks field loses focus. This is useful when you want to update the preview only when the user has finished typing or editing a field.

To change the default strategy to `blur`, use the `updateStrategy` property:

```yaml 
type: preview
updateStrategy: blur
```

**Comment by arnoson** [comment]
Awesome, thanks!
